In [ ]:
import pandas as pd


def load(path):
    df = pd.read_csv(path, index_col=0)
    if "coverage" in df.columns:
        df["coverage"] = (df["coverage"] * 100).round(2).astype(str) + "%"
    return df.round(4)

## FR

In [ ]:
load("interscada_fr_report.csv")

,n,coverage,mse,rmse,mae,abs_err_min,abs_err_q25,abs_err_q50,abs_err_q75,abs_err_q90,abs_err_q95,abs_err_q99,abs_err_max
crit_gen_true,,,,,,,,,,,,,
palue7paluet1,2,3.7%,0.0001,0.0117,0.0117,0.0117,0.0117,0.0117,0.0117,0.0117,0.0117,0.0117,0.0117
flama7flamat1,8,3.74%,0.0004,0.0192,0.0190,0.0176,0.0176,0.0176,0.0190,0.0234,0.0234,0.0234,0.0234
palue7paluet3,6,3.77%,0.0366,0.1913,0.1504,0.0176,0.0454,0.1289,0.2607,0.3047,0.3047,0.3047,0.3047
penly7penlyt2,2,3.7%,0.0289,0.1699,0.1699,0.1699,0.1699,0.1699,0.1699,0.1699,0.1699,0.1699,0.1699
penly7penlyt1,2,7.41%,0.0496,0.2227,0.2227,0.2227,0.2227,0.2227,0.2227,0.2227,0.2227,0.2227,0.2227
palue7paluet4,4,3.74%,0.0621,0.2493,0.2285,0.1289,0.1289,0.2285,0.3281,0.3281,0.3281,0.3281,0.3281
NaN,0,0.0%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
load("risk_coverage_interscada_fr.csv")

                      metric coverage   n     mae    rmse     q90     q95
0       location_weight_mass   100.0%  24  0.1157  0.1618  0.3047  0.3246
1       location_weight_mass    95.0%  23  0.1200  0.1652  0.3047  0.3258
2       location_weight_mass    90.0%  22  0.1246  0.1689  0.3047  0.3270
3       location_weight_mass    80.0%  20  0.1351  0.1770  0.3070  0.3281
4       location_weight_mass    70.0%  17  0.1558  0.1919  0.3141  0.3281
5       location_weight_mass    50.0%  12  0.1704  0.2039  0.3258  0.3281
6                      n_eff   100.0%  24  0.1157  0.1618  0.3047  0.3246
7                      n_eff    95.0%  23  0.1134  0.1614  0.3047  0.3258
8                      n_eff    90.0%  22  0.1108  0.1610  0.3047  0.3270
9                      n_eff    80.0%  20  0.1102  0.1614  0.3070  0.3281
10                     n_eff    70.0%  17  0.1082  0.1635  0.3141  0.3281
11                     n_eff    50.0%  12  0.0757  0.1309  0.2871  0.3047
12               n_neighbors   100.0%  24  0.1157  0.1618  0.3047  0.3246
13               n_neighbors    95.0%  23  0.1134  0.1614  0.3047  0.3258
14               n_neighbors    90.0%  22  0.1108  0.1610  0.3047  0.3270
15               n_neighbors    80.0%  20  0.1102  0.1614  0.3070  0.3281
16               n_neighbors    70.0%  17  0.1082  0.1635  0.3141  0.3281
17               n_neighbors    50.0%  12  0.0757  0.1309  0.2871  0.3047
18  neighborhood_compactness   100.0%  18  0.1094  0.1618  0.3117  0.3281
19  neighborhood_compactness    95.0%  18  0.1094  0.1618  0.3117  0.3281
20  neighborhood_compactness    90.0%  17  0.1148  0.1664  0.3141  0.3281
21  neighborhood_compactness    80.0%  15  0.1277  0.1770  0.3187  0.3281
22  neighborhood_compactness    70.0%  13  0.1203  0.1668  0.3047  0.3141
23  neighborhood_compactness    50.0%   9  0.1094  0.1618  0.3094  0.3187
24              distance_min   100.0%  24  0.1157  0.1618  0.3047  0.3246
25              distance_min    95.0%  23  0.1134  0.1614  0.3047  0.3258
26              distance_min    90.0%  22  0.1084  0.1581  0.3047  0.3270
27              distance_min    80.0%  20  0.1178  0.1657  0.3070  0.3281
28              distance_min    70.0%  17  0.1168  0.1610  0.3047  0.3094
29              distance_min    50.0%  12  0.1157  0.1618  0.2965  0.3152
30             distance_mean   100.0%  24  0.1157  0.1618  0.3047  0.3246
31             distance_mean    95.0%  23  0.1134  0.1614  0.3047  0.3258
32             distance_mean    90.0%  22  0.1084  0.1581  0.3047  0.3270
33             distance_mean    80.0%  20  0.1178  0.1657  0.3070  0.3281
34             distance_mean    70.0%  17  0.1168  0.1610  0.3047  0.3094
35             distance_mean    50.0%  12  0.1157  0.1618  0.2965  0.3152
36           distance_median   100.0%  24  0.1157  0.1618  0.3047  0.3246
37           distance_median    95.0%  23  0.1134  0.1614  0.3047  0.3258
38           distance_median    90.0%  22  0.1084  0.1581  0.3047  0.3270
39           distance_median    80.0%  20  0.1178  0.1657  0.3070  0.3281
40           distance_median    70.0%  17  0.1168  0.1610  0.3047  0.3094
41           distance_median    50.0%  12  0.1157  0.1618  0.2965  0.3152
42           distance_spread   100.0%  24  0.1157  0.1618  0.3047  0.3246
43           distance_spread    95.0%  23  0.1134  0.1614  0.3047  0.3258
44           distance_spread    90.0%  22  0.1177  0.1650  0.3047  0.3270
45           distance_spread    80.0%  20  0.1277  0.1730  0.3070  0.3281
46           distance_spread    70.0%  17  0.1286  0.1698  0.3047  0.3094
47           distance_spread    50.0%  12  0.1157  0.1618  0.2965  0.3152
48             distance_norm   100.0%  24  0.1157  0.1618  0.3047  0.3246
49             distance_norm    95.0%  23  0.1134  0.1614  0.3047  0.3258
50             distance_norm    90.0%  22  0.1177  0.1650  0.3047  0.3270
51             distance_norm    80.0%  20  0.1277  0.1730  0.3070  0.3281
52             distance_norm    70.0%  17  0.1286  0.1698  0.3047  0.3094
53             distance_norm    50.0%  12  0.1157  0.1618  0.2965  0.3152

## PL

In [ ]:
load("interscada_pl_report.csv")

,n,coverage,mse,rmse,mae,abs_err_min,abs_err_q25,abs_err_q50,abs_err_q75,abs_err_q90,abs_err_q95,abs_err_q99,abs_err_max
crit_gen_true,,,,,,,,,,,,,
<na>,5499,99.8%,0.0000,0.0000,0.0000,0.0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
38,2471,98.88%,0.0006,0.0244,0.0164,0.0,0.0055,0.0118,0.0210,0.0350,0.0465,0.0926,0.1898
31,8884,99.83%,0.0007,0.0265,0.0173,0.0,0.0041,0.0106,0.0246,0.0401,0.0530,0.0884,0.3076
37,5837,99.59%,0.0009,0.0295,0.0201,0.0,0.0053,0.0132,0.0278,0.0458,0.0603,0.1042,0.2235
32,2565,98.65%,0.0010,0.0317,0.0210,0.0,0.0049,0.0140,0.0293,0.0485,0.0640,0.1013,0.2448
30,1775,98.28%,0.0010,0.0310,0.0211,0.0,0.0072,0.0157,0.0280,0.0444,0.0581,0.0910,0.4151
35,3106,98.76%,0.0011,0.0330,0.0211,0.0,0.0059,0.0140,0.0272,0.0470,0.0658,0.1324,0.3139
36,2650,99.07%,0.0011,0.0325,0.0214,0.0,0.0060,0.0150,0.0269,0.0460,0.0658,0.1190,0.3201
39,390,89.86%,0.0014,0.0372,0.0214,0.0,0.0058,0.0143,0.0279,0.0424,0.0566,0.1589,0.2950
34,13494,99.99%,0.0009,0.0306,0.0214,0.0,0.0064,0.0150,0.0293,0.0486,0.0629,0.0961,0.2627
33,990,97.25%,0.0011,0.0339,0.0234,0.0,0.0084,0.0181,0.0305,0.0477,0.0616,0.1279,0.2233

In [ ]:
load("risk_coverage_interscada_pl.csv")

                      metric coverage      n     mae    rmse     q90     q95
0       location_weight_mass   100.0%  47661  0.0177  0.0281  0.0426  0.0576
1       location_weight_mass    95.0%  45278  0.0169  0.0263  0.0410  0.0549
2       location_weight_mass    90.0%  42895  0.0166  0.0257  0.0402  0.0538
3       location_weight_mass    80.0%  38129  0.0162  0.0256  0.0399  0.0536
4       location_weight_mass    70.0%  33363  0.0164  0.0261  0.0407  0.0549
5       location_weight_mass    50.0%  23831  0.0165  0.0265  0.0408  0.0554
6                      n_eff   100.0%  47661  0.0177  0.0281  0.0426  0.0576
7                      n_eff    95.0%  45278  0.0178  0.0277  0.0428  0.0575
8                      n_eff    90.0%  42895  0.0181  0.0277  0.0433  0.0579
9                      n_eff    80.0%  38129  0.0181  0.0277  0.0434  0.0580
10                     n_eff    70.0%  33363  0.0177  0.0271  0.0427  0.0571
11                     n_eff    50.0%  23831  0.0169  0.0261  0.0411  0.0552
12               n_neighbors   100.0%  47661  0.0177  0.0281  0.0426  0.0576
13               n_neighbors    95.0%  45278  0.0177  0.0277  0.0426  0.0574
14               n_neighbors    90.0%  42895  0.0175  0.0276  0.0425  0.0574
15               n_neighbors    80.0%  38129  0.0173  0.0273  0.0423  0.0572
16               n_neighbors    70.0%  33363  0.0168  0.0269  0.0415  0.0568
17               n_neighbors    50.0%  23831  0.0150  0.0241  0.0370  0.0499
18  neighborhood_compactness   100.0%  47661  0.0177  0.0281  0.0426  0.0576
19  neighborhood_compactness    95.0%  45278  0.0181  0.0286  0.0434  0.0586
20  neighborhood_compactness    90.0%  42895  0.0185  0.0290  0.0440  0.0593
21  neighborhood_compactness    80.0%  38129  0.0188  0.0296  0.0448  0.0607
22  neighborhood_compactness    70.0%  33363  0.0192  0.0300  0.0457  0.0615
23  neighborhood_compactness    50.0%  23831  0.0200  0.0306  0.0478  0.0640
24              distance_min   100.0%  47661  0.0177  0.0281  0.0426  0.0576
25              distance_min    95.0%  45278  0.0176  0.0276  0.0424  0.0570
26              distance_min    90.0%  42895  0.0175  0.0268  0.0421  0.0560
27              distance_min    80.0%  38129  0.0173  0.0263  0.0412  0.0548
28              distance_min    70.0%  33363  0.0175  0.0266  0.0416  0.0554
29              distance_min    50.0%  23831  0.0172  0.0263  0.0413  0.0547
30             distance_mean   100.0%  47661  0.0177  0.0281  0.0426  0.0576
31             distance_mean    95.0%  45278  0.0180  0.0283  0.0433  0.0582
32             distance_mean    90.0%  42895  0.0185  0.0287  0.0440  0.0590
33             distance_mean    80.0%  38129  0.0186  0.0282  0.0441  0.0589
34             distance_mean    70.0%  33363  0.0193  0.0289  0.0455  0.0606
35             distance_mean    50.0%  23831  0.0190  0.0283  0.0450  0.0595
36           distance_median   100.0%  47661  0.0177  0.0281  0.0426  0.0576
37           distance_median    95.0%  45278  0.0181  0.0284  0.0433  0.0582
38           distance_median    90.0%  42895  0.0185  0.0287  0.0441  0.0590
39           distance_median    80.0%  38129  0.0185  0.0282  0.0441  0.0590
40           distance_median    70.0%  33363  0.0190  0.0288  0.0451  0.0600
41           distance_median    50.0%  23831  0.0187  0.0279  0.0444  0.0584
42           distance_spread   100.0%  47661  0.0177  0.0281  0.0426  0.0576
43           distance_spread    95.0%  45278  0.0181  0.0285  0.0433  0.0583
44           distance_spread    90.0%  42895  0.0186  0.0289  0.0441  0.0592
45           distance_spread    80.0%  38129  0.0193  0.0294  0.0453  0.0607
46           distance_spread    70.0%  33363  0.0201  0.0304  0.0470  0.0624
47           distance_spread    50.0%  23831  0.0194  0.0292  0.0456  0.0608
48             distance_norm   100.0%  47661  0.0177  0.0281  0.0426  0.0576
49             distance_norm    95.0%  45278  0.0172  0.0271  0.0412  0.0552
50             distance_norm    90.0%  42895  0.0170  0.0267  0.0408  0.0547
51             distance_norm    80.0%  38129  0.0167  0.0267  0.0404  0.0548
52             distance_norm    70.0%  33363  0.0165  0.0265  0.0401  0.0549
53             distance_norm    50.0%  23831  0.0152  0.0253  0.0371  0.0534

In [ ]:
with pd.ExcelWriter("interscada_benchmark.xlsx", engine="openpyxl") as writer:
    load("interscada_fr_report.csv").to_excel(writer, sheet_name="FR by crit_gen")
    load("risk_coverage_interscada_fr.csv").to_excel(writer, sheet_name="FR risk coverage")
    load("interscada_pl_report.csv").to_excel(writer, sheet_name="PL by crit_gen")
    load("risk_coverage_interscada_pl.csv").to_excel(writer, sheet_name="PL risk coverage")