In [ ]:
import joblib
import pandas as pd

## Poland dataset (modified BUS39)

In [ ]:
lf = pd.read_pickle("../data/interscada/interim/pl/lf.pkl")

with pd.option_context("display.max_rows", None):
    display(lf.T)

case_name,SET_0001__Point_no.___10,SET_0001__Point_no.___11,SET_0001__Point_no.___12,SET_0001__Point_no.___13,SET_0001__Point_no.___14,SET_0001__Point_no.___15,SET_0001__Point_no.___16,SET_0001__Point_no.___17,SET_0001__Point_no.___18,SET_0001__Point_no.___19,...,SET_0225__Point_no.___16,SET_0225__Point_no.___17,SET_0225__Point_no.____2,SET_0225__Point_no.____3,SET_0225__Point_no.____4,SET_0225__Point_no.____5,SET_0225__Point_no.____6,SET_0225__Point_no.____7,SET_0225__Point_no.____8,SET_0225__Point_no.____9
_BUS01_345._[pu],1.0477,1.04643,1.04513,1.04381,1.04245,1.04107,1.03967,1.03823,1.03676,1.03526,...,1.05518,1.0522,1.06126,1.06098,1.06054,1.05995,1.0592,1.05986,1.06047,1.06076
_BUS01_345.__[deg],-6.6,-6.6,-6.59,-6.59,-6.59,-6.59,-6.6,-6.6,-6.6,-6.61,...,5.68,5.7,-5.68,-5.33,-4.98,-4.63,-4.29,-3.29,-2.18,-1.06
_BUS02_345._[pu],1.05794,1.05697,1.05597,1.05495,1.05391,1.05284,1.05175,1.05063,1.04949,1.04832,...,1.04947,1.04392,1.06534,1.06428,1.06296,1.06135,1.05945,1.0592,1.059,1.05852
_BUS02_345.__[deg],-0.15,0.03,0.21,0.4,0.58,0.76,0.95,1.13,1.32,1.5,...,2.73,2.75,-1.88,-1.6,-1.32,-1.05,-0.77,-0.34,0.12,0.58
_BUS03_345._[pu],1.05745,1.05593,1.05437,1.05278,1.05115,1.04949,1.04779,1.04606,1.04428,1.04246,...,1.03929,1.0293,1.06875,1.06796,1.06679,1.06524,1.06327,1.06214,1.06081,1.05904
_BUS03_345.__[deg],-0.53,-0.34,-0.15,0.05,0.24,0.43,0.63,0.82,1.02,1.21,...,-2.74,-2.79,-3.13,-3.25,-3.38,-3.52,-3.66,-3.59,-3.49,-3.39
_BUS04_345._[pu],1.04605,1.04407,1.04206,1.04,1.0379,1.03576,1.03358,1.03135,1.02908,1.02676,...,1.04059,1.03207,1.06433,1.06405,1.06349,1.06263,1.06147,1.06067,1.05962,1.05818
_BUS04_345.__[deg],-0.99,-0.79,-0.58,-0.38,-0.18,0.03,0.23,0.44,0.64,0.85,...,-3.6,-3.66,-3.56,-3.82,-4.09,-4.37,-4.65,-4.61,-4.53,-4.45
_BUS05_345._[pu],1.04691,1.04503,1.0431,1.04113,1.03913,1.03708,1.03499,1.03285,1.03067,1.02845,...,1.04904,1.0431,1.06575,1.06571,1.06546,1.065,1.06432,1.06392,1.0633,1.06235
_BUS05_345.__[deg],-0.95,-0.74,-0.53,-0.32,-0.1,0.11,0.32,0.54,0.76,0.98,...,-1.99,-2.04,-3.27,-3.49,-3.72,-3.96,-4.2,-4.05,-3.85,-3.64
_BUS06_345._[pu],1.04613,1.04434,1.04251,1.04065,1.03874,1.0368,1.03481,1.03278,1.03071,1.0286,...,1.04862,1.0431,1.06401,1.064,1.06378,1.06338,1.06276,1.06241,1.06184,1.06097
_BUS06_345.__[deg],-0.49,-0.27,-0.04,0.19,0.42,0.65,0.88,1.11,1.35,1.58,...,-1.71,-1.76,-2.96,-3.19,-3.42,-3.66,-3.91,-3.76,-3.56,-3.36
_BUS07_345._[pu],1.03939,1.03729,1.03516,1.03298,1.03076,1.02849,1.02618,1.02383,1.02142,1.01897,...,1.0456,1.04014,1.06123,1.06128,1.06112,1.06076,1.06019,1.05992,1.05941,1.05856
_BUS07_345.__[deg],-2.29,-2.12,-1.96,-1.79,-1.62,-1.45,-1.28,-1.11,-0.94,-0.76,...,-1.88,-1.93,-3.99,-4.18,-4.37,-4.57,-4.78,-4.56,-4.28,-4.0
_BUS08_345._[pu],1.03833,1.03618,1.03398,1.03175,1.02947,1.02714,1.02477,1.02235,1.01988,1.01737,...,1.04534,1.03993,1.06099,1.06106,1.06094,1.0606,1.06005,1.05983,1.05935,1.05852
_BUS08_345.__[deg],-2.86,-2.71,-2.56,-2.41,-2.26,-2.11,-1.96,-1.81,-1.65,-1.5,...,-1.75,-1.8,-4.3,-4.47,-4.65,-4.83,-5.01,-4.76,-4.44,-4.11
_BUS09_345._[pu],1.04392,1.04227,1.04058,1.03886,1.03711,1.03533,1.0335,1.03165,1.02975,1.02782,...,1.05179,1.04871,1.06231,1.06259,1.06271,1.06268,1.0625,1.06279,1.06283,1.06248
_BUS09_345.__[deg],-7.44,-7.45,-7.45,-7.46,-7.47,-7.48,-7.49,-7.51,-7.52,-7.54,...,3.71,3.71,-6.5,-6.34,-6.18,-6.02,-5.86,-4.96,-3.94,-2.91
_BUS10_345._[pu],1.04941,1.04793,1.04642,1.04487,1.04329,1.04167,1.04002,1.03833,1.03661,1.03484,...,1.047,1.04107,1.06316,1.06308,1.06281,1.06234,1.06168,1.06118,1.06047,1.05949
_BUS10_345.__[deg],1.61,1.91,2.2,2.5,2.8,3.1,3.4,3.71,4.01,4.32,...,-1.87,-1.93,-1.83,-2.13,-2.44,-2.75,-3.08,-3.04,-2.95,-2.87
_BUS11_345._[pu],1.0477,1.04608,1.04443,1.04273,1.04101,1.03924,1.03744,1.0356,1.03371,1.03179,...,1.0473,1.04147,1.06327,1.06321,1.06296,1.06252,1.06187,1.06142,1.06076,1.05982
_BUS11_345.__[deg],0.9,1.17,1.45,1.72,2.0,2.27,2.55,2.83,3.11,3.4,...,-1.84,-1.9,-2.22,-2.5,-2.78,-3.07,-3.37,-3.3,-3.17,-3.05
_BUS12_345._[pu],1.04352,1.04155,1.03955,1.03751,1.03543,1.03332,1.03116,1.02896,1.02671,1.02443,...,1.04519,1.03862,1.0631,1.06301,1.06271,1.06219,1.06146,1.0609,1.06012,1.05903
_BUS12_345.__[deg],1.08,1.35,1.63,1.91,2.19,2.48,2.76,3.05,3.33,3.62,...,-2.25,-2.31,-2.21,-2.51,-2.82,-3.13,-3.45,-3.42,-3.33,-3.24
_BUS13_345._[pu],1.04955,1.04795,1.0463,1.04462,1.0429,1.04115,1.03936,1.03753,1.03565,1.03374,...,1.04474,1.03761,1.06409,1.06397,1.06363,1.06305,1.06225,1.0616,1.06072,1.05952
_BUS13_345.__[deg],1.33,1.61,1.9,2.18,2.47,2.76,3.05,3.35,3.64,3.94,...,-2.62,-2.68,-2.15,-2.48,-2.81,-3.14,-3.49,-3.49,-3.44,-3.4
_BUS14_345._[pu],1.05165,1.04982,1.04796,1.04606,1.04412,1.04213,1.04011,1.03804,1.03592,1.03376,...,1.04031,1.03021,1.06687,1.06666,1.06615,1.06533,1.0642,1.06324,1.06197,1.06029
_BUS14_345.__[deg],0.72,0.98,1.24,1.5,1.77,2.04,2.3,2.57,2.84,3.12,...,-4.47,-4.55,-2.89,-3.27,-3.66,-4.06,-4.47,-4.57,-4.62,-4.67
_BUS15_345._[pu],1.06038,1.05851,1.05659,1.05463,1.05262,1.05056,1.04846,1.04631,1.04412,1.04187,...,1.02865,1.00977,1.07022,1.06993,1.0692,1.06803,1.0664,1.06474,1.06263,1.05999
_BUS15_345.__[deg],2.27,2.58,2.9,3.21,3.53,3.85,4.17,4.49,4.81,5.14,...,-9.96,-10.17,-3.3,-4.02,-4.75,-5.49,-6.25,-6.76,-7.25,-7.75
_BUS16_345._[pu],1.07217,1.07061,1.06901,1.06737,1.06569,1.06396,1.06218,1.06036,1.05848,1.05656,...,1.02942,1.00698,1.07511,1.07476,1.07395,1.07266,1.07088,1.06901,1.06669,1.06383
_BUS16_345.__[deg],3.83,4.19,4.55,4.92,5.28,5.65,6.02,6.4,6.77,7.15,...,-11.76,-12.02,-2.92,-3.79,-4.66,-5.55,-6.45,-7.14,-7.82,-8.51
_BUS17_345._[pu],1.06571,1.06411,1.06245,1.06076,1.05902,1.05723,1.0554,1.05352,1.0516,1.04962,...,1.03032,1.01292,1.07276,1.07224,1.07125,1.06976,1.06776,1.06591,1.06365,1.06086
_BUS17_345.__[deg],1.97,2.24,2.52,2.79,3.07,3.34,3.62,3.9,4.18,4.47,...,-8.09,-8.24,-2.86,-3.42,-3.98,-4.56,-5.14,-5.54,-5.92,-6.31
_BUS18_345._[pu],1.06195,1.06032,1.05865,1.05693,1.05518,1.05338,1.05154,1.04966,1.04772,1.04575,...,1.03283,1.0182,1.07138,1.07076,1.06969,1.06815,1.06613,1.06449,1.06251,1.06001
_BUS18_345.__[deg],0.77,1.01,1.24,1.48,1.71,1.95,2.19,2.43,2.67,2.91,...,-6.21,-6.31,-3.12,-3.51,-3.91,-4.32,-4.73,-4.96,-5.15,-5.36
_BUS19_345._[pu],1.06809,1.06727,1.06643,1.06557,1.06468,1.06377,1.06284,1.06188,1.06089,1.05988,...,1.01024,0.96411,1.07079,1.06981,1.0684,1.06655,1.06424,1.06161,1.05851,1.0549
_BUS19_345.__[deg],8.45,8.97,9.5,10.03,10.56,11.1,11.64,12.18,12.73,13.28,...,-24.21,-26.56,-0.18,-2.01,-3.86,-5.73,-7.63,-9.32,-11.02,-12.74
_BUS20_110._[pu],1.00563,1.00492,1.00419,1.00344,1.00267,1.00189,1.0011,1.00029,0.99945,0.99861,...,0.93342,0.87736,1.00865,1.00644,1.00387,1.00094,0.99764,0.99403,0.99002,0.98558
_BUS20_110.__[deg],8.66,9.21,9.75,10.3,10.85,11.4,11.96,12.52,13.09,13.66,...,-37.18,-42.06,-0.49,-3.1,-5.73,-8.4,-11.1,-13.61,-16.14,-18.72
_BUS21_345._[pu],1.09597,1.09466,1.09331,1.09193,1.0905,1.08903,1.08752,1.08597,1.08438,1.08274,...,1.04638,1.02915,1.08086,1.08061,1.08002,1.07909,1.0778,1.07644,1.07477,1.07269
_BUS21_345.__[deg],6.31,6.77,7.22,7.69,8.15,8.62,9.09,9.57,10.04,10.53,...,-11.44,-11.2,-3.62,-4.49,-5.36,-6.25,-7.16,-7.85,-8.53,-9.22
_BUS22_345._[pu],1.08202,1.0812,1.08034,1.07947,1.07856,1.07763,1.07667,1.07569,1.07468,1.07363,...,1.05844,1.04881,1.07743,1.0773,1.07699,1.0765,1.07582,1.0751,1.07422,1.07313
_BUS22_345.__[deg],9.32,9.88,10.44,11.0,11.56,12.13,12.7,13.28,13.86,14.44,...,-7.41,-6.59,-0.82,-1.68,-2.56,-3.44,-4.34,-5.04,-5.71,-6.4
_BUS23_345._[pu],1.07423,1.07328,1.0723,1.07129,1.07025,1.06918,1.06809,1.06696,1.0658,1.06461,...,1.0543,1.04433,1.07393,1.0738,1.07348,1.07298,1.07228,1.07156,1.07065,1.06954
_BUS23_345.__[deg],9.32,9.88,10.43,11.0,11.56,12.13,12.7,13.28,13.86,14.44,...,-6.86,-5.98,-0.4,-1.27,-2.14,-3.03,-3.93,-4.62,-5.29,-5.98
_BUS24_345._[pu],1.07501,1.07356,1.07206,1.07052,1.06893,1.0673,1.06563,1.0639,1.06214,1.06032,...,1.03491,1.01401,1.07725,1.07693,1.07619,1.07502,1.07339,1.07169,1.06957,1.06696
_BUS24_345.__[deg],4.14,4.51,4.89,5.26,5.64,6.03,6.41,6.8,7.19,7.58,...,-11.36,-11.46,-2.86,-3.73,-4.6,-5.49,-6.39,-7.08,-7.76,-8.45
_BUS25_345._[pu],1.06646,1.06578,1.06509,1.06438,1.06364,1.06288,1.0621,1.0613,1.06047,1.05963,...,1.0582,1.05354,1.07278,1.07332,1.07357,1.07353,1.07319,1.07234,1.07122,1.06988
_BUS25_345.__[deg],1.56,1.76,1.97,2.18,2.38,2.59,2.8,3.01,3.22,3.43,...,4.58,4.59,-0.15,0.33,0.82,1.32,1.81,2.19,2.55,2.91
_BUS26_345._[pu],1.05287,1.0519,1.05089,1.04986,1.04879,1.0477,1.04657,1.04542,1.04423,1.043,...,1.03308,1.02521,1.05886,1.05857,1.05793,1.05694,1.05558,1.05419,1.05255,1.05059
_BUS26_345.__[deg],1.35,1.47,1.6,1.72,1.84,1.96,2.09,2.21,2.33,2.46,...,-0.15,-0.17,-0.29,-0.29,-0.29,-0.29,-0.29,-0.27,-0.26,-0.25
_BUS27_345._[pu],1.05722,1.05573,1.05421,1.05264,1.05103,1.04938,1.04769,1.04596,1.04418,1.04235,...,1.02865,1.01555,1.06566,1.06513,1.06415,1.06271,1.0608,1.05899,1.05685,1.05426
_BUS27_345.__[deg],0.88,1.06,1.23,1.41,1.59,1.77,1.95,2.14,2.32,2.5,...,-4.94,-5.02,-2.18,-2.48,-2.78,-3.09,-3.41,-3.62,-3.82,-4.03
_BUS28_345._[pu],1.02755,1.02691,1.02626,1.02559,1.02491,1.02421,1.02349,1.02276,1.022,1.02123,...,1.02066,1.01701,1.03256,1.03243,1.03214,1.03168,1.03105,1.0304,1.02965,1.02875
_BUS28_345.__[deg],2.47,2.47,2.47,2.47,2.47,2.46,2.46,2.46,2.46,2.46,...,2.51,2.5,2.45,2.45,2.45,2.45,2.45,2.46,2.46,2.47
_BUS29_345._[pu],1.02604,1.02559,1.02512,1.02464,1.02415,1.02365,1.02314,1.02261,1.02207,1.02152,...,1.02087,1.0182,1.02957,1.02948,1.02926,1.02892,1.02846,1.02799,1.02744,1.02678
_BUS29_345.__[deg],3.71,3.71,3.71,3.71,3.71,3.71,3.71,3.71,3.71,3.7,...,3.75,3.74,3.71,3.71,3.71,3.71,3.71,3.71,3.71,3.72
_BUS30_13.08_[pu],1.0475,1.0475,1.0475,1.0475,1.0475,1.0475,1.0475,1.0475,1.0475,1.0475,...,1.0475,1.04487,1.0475,1.0475,1.0475,1.0475,1.0475,1.0475,1.0475,1.0475
_BUS30_13.08__[deg],0.51,0.72,0.92,1.13,1.33,1.54,1.74,1.95,2.15,2.36,...,5.2,5.24,-1.3,-0.92,-0.54,-0.15,0.23,0.96,1.75,2.54
_BUS31_13.08_[pu],0.982,0.982,0.982,0.982,0.982,0.982,0.982,0.982,0.982,0.982,...,0.982,0.982,0.982,0.982,0.982,0.982,0.982,0.982,0.982,0.982
_BUS31_13.08__[deg],5.23,5.65,6.07,6.49,6.91,7.34,7.76,8.19,8.63,9.06,...,2.41,2.38,1.1,0.87,0.64,0.4,0.16,0.3,0.51,0.72
_BUS32_13.08_[pu],0.9831,0.9831,0.9831,0.9831,0.9831,0.9831,0.9831,0.9831,0.9831,0.9831,...,0.9831,0.9831,0.9831,0.9831,0.9831,0.9831,0.9831,0.9831,0.9831,0.9831
_BUS32_13.08__[deg],6.9,7.37,7.84,8.31,8.79,9.27,9.75,10.23,10.71,11.2,...,1.94,1.91,1.93,1.62,1.32,1.01,0.69,0.72,0.81,0.9
_BUS33_13.08_[pu],0.9972,0.9972,0.9972,0.9972,0.9972,0.9972,0.9972,0.9972,0.9972,0.9972,...,0.9972,0.96433,0.9972,0.9972,0.9972,0.9972,0.9972,0.9972,0.9972,0.9972
_BUS33_13.08__[deg],12.09,12.73,13.37,14.02,14.66,15.32,15.97,16.63,17.3,17.96,...,-21.6,-23.76,2.44,0.61,-1.24,-3.11,-5.01,-6.7,-8.4,-10.12
_BUS34_13.08_[pu],1.0123,1.0123,1.0123,1.0123,1.0123,1.0123,1.0123,1.0123,1.0123,1.0123,...,1.0021,0.95052,1.0123,1.0123,1.0123,1.0123,1.0123,1.0123,1.0123,1.0123
_BUS34_13.08__[deg],13.17,13.85,14.54,15.23,15.93,16.63,17.33,18.04,18.75,19.46,...,-33.85,-38.33,2.74,0.13,-2.5,-5.16,-7.86,-10.38,-12.91,-15.48
_BUS35_13.08_[pu],1.0493,1.0493,1.0493,1.0493,1.0493,1.0493,1.0493,1.0493,1.0493,1.0493,...,1.0493,1.0493,1.0493,1.0493,1.0493,1.0493,1.0493,1.0493,1.0493,1.0493
_BUS35_13.08__[deg],12.61,13.27,13.94,14.6,15.27,15.95,16.63,17.31,18.0,18.69,...,-3.99,-2.71,1.56,0.7,-0.18,-1.06,-1.96,-2.66,-3.33,-4.01
_BUS36_13.08_[pu],1.0635,1.0635,1.0635,1.0635,1.0635,1.0635,1.0635,1.0635,1.0635,1.0635,...,1.0635,1.0635,1.0635,1.0635,1.0635,1.0635,1.0635,1.0635,1.0635,1.0635
_BUS36_13.08__[deg],15.4,16.15,16.91,17.66,18.42,19.19,19.96,20.73,21.51,22.3,...,-0.59,1.15,3.98,3.11,2.24,1.36,0.46,-0.23,-0.9,-1.59
_BUS37_13.08_[pu],1.0278,1.0278,1.0278,1.0278,1.0278,1.0278,1.0278,1.0278,1.0278,1.0278,...,1.0278,1.0278,1.0278,1.0278,1.0278,1.0278,1.0278,1.0278,1.0278,1.0278
_BUS37_13.08__[deg],7.1,7.49,7.87,8.25,8.64,9.02,9.41,9.8,10.19,10.58,...,13.13,13.17,4.67,6.01,7.37,8.75,10.14,10.64,11.01,11.38
_BUS38_13.08_[pu],1.0175,1.0175,1.0175,1.0175,1.0175,1.0175,1.0175,1.0175,1.0175,1.0175,...,1.0175,1.0175,1.0175,1.0175,1.0175,1.0175,1.0175,1.0175,1.0175,1.0175
_BUS38_13.08__[deg],7.15,7.15,7.15,7.15,7.15,7.15,7.15,7.15,7.15,7.15,...,7.15,7.15,7.15,7.15,7.15,7.15,7.15,7.15,7.15,7.15
_BUS39_13.08_[pu],1.03,1.03,1.03,1.03,1.03,1.03,1.03,1.03,1.03,1.03,...,1.03,1.03,1.03,1.03,1.03,1.03,1.03,1.03,1.03,1.03
_BUS39_13.08__[deg],-9.81,-9.9,-9.98,-10.07,-10.16,-10.25,-10.34,-10.43,-10.53,-10.63,...,12.1,12.12,-7.34,-6.83,-6.32,-5.81,-5.29,-3.61,-1.74,0.16
_BUS40_345._[pu],1.03229,1.0313,1.03031,1.02929,1.02826,1.02722,1.02615,1.02507,1.02398,1.02286,...,1.03945,1.03808,1.04377,1.04383,1.04382,1.04373,1.04356,1.0439,1.04412,1.04414
_BUS40_345.__[deg],-10.56,-10.67,-10.78,-10.89,-11.0,-11.12,-11.23,-11.35,-11.47,-11.6,...,7.54,7.56,-7.99,-7.59,-7.2,-6.8,-6.41,-5.06,-3.55,-2.02
_BUS41_345._[pu],1.05172,1.05077,1.0498,1.04879,1.04776,1.04669,1.04559,1.04447,1.04331,1.04212,...,1.03233,1.02465,1.05748,1.0572,1.05658,1.05561,1.05428,1.05293,1.05133,1.04942
_BUS41_345.__[deg],1.42,1.53,1.65,1.77,1.89,2.01,2.12,2.24,2.36,2.48,...,-0.02,-0.04,-0.17,-0.16,-0.16,-0.16,-0.16,-0.15,-0.14,-0.12
"_Gen_bus_no,_status",30,30,30,30,30,30,30,30,30,30,...,30,30,30,30,30,30,30,30,30,30
_Gen_P_MW,69.45,71.61,73.78,75.95,78.13,80.3,82.47,84.65,86.83,89.01,...,255.0,255.0,60.64,71.48,82.44,93.51,104.7,135.56,169.83,204.47
_Gen_Q_mvar,89.32,94.85,100.51,106.3,112.22,118.27,124.46,130.79,137.27,143.89,...,142.38,158.0,47.44,53.52,61.15,70.39,81.29,83.34,85.38,89.17
"_Gen_bus_no,_status.01",31,31,31,31,31,31,31,31,31,31,...,31,31,31,31,31,31,31,31,31,31
_Gen_P_MW.01,388.9,401.04,413.18,425.34,437.5,449.68,461.86,474.05,486.25,498.45,...,280.0,280.0,280.0,280.0,280.0,280.0,280.0,280.0,280.0,280.0
_Gen_Q_mvar.01,38.91,46.82,54.9,63.18,71.64,80.29,89.14,98.19,107.45,116.91,...,19.53,39.77,-37.17,-37.11,-36.33,-34.83,-32.58,-31.27,-29.18,-25.96
"_Gen_bus_no,_status.02",32,32,32,32,32,32,32,32,32,32,...,32,32,32,32,32,32,32,32,32,32
_Gen_P_MW.02,444.45,458.33,472.21,486.1,500.0,513.92,527.84,541.77,555.71,569.66,...,320.0,320.0,320.0,320.0,320.0,320.0,320.0,320.0,320.0,320.0
_Gen_Q_mvar.02,32.06,40.19,48.52,57.05,65.79,74.74,83.89,93.27,102.87,112.69,...,33.32,60.51,-41.15,-40.78,-39.54,-37.4,-34.33,-32.01,-28.76,-24.24
"_Gen_bus_no,_status.03",33,33,33,33,33,33,33,33,33,33,...,33,33,33,33,33,33,33,33,33,33
_Gen_P_MW.03,444.45,458.33,472.21,486.1,500.0,513.92,527.84,541.77,555.71,569.66,...,320.0,320.0,320.0,320.0,320.0,320.0,320.0,320.0,320.0,320.0
_Gen_Q_mvar.03,-14.88,-9.3,-3.55,2.38,8.48,14.78,21.26,27.93,34.8,41.86,...,363.8,421.4,-33.26,-26.86,-17.62,-5.48,9.67,26.91,47.21,70.93
"_Gen_bus_no,_status.04",34,34,34,34,34,34,34,34,34,34,...,34,34,34,34,34,34,34,34,34,34
_Gen_P_MW.04,444.45,458.33,472.21,486.1,500.0,513.92,527.84,541.77,555.71,569.66,...,320.0,320.0,320.0,320.0,320.0,320.0,320.0,320.0,320.0,320.0
_Gen_Q_mvar.04,83.04,87.44,91.97,96.62,101.39,106.29,111.32,116.48,121.77,127.2,...,421.4,421.4,64.05,76.38,90.66,106.96,125.35,145.46,167.77,192.51
"_Gen_bus_no,_status.05",35,35,35,35,35,35,35,35,35,35,...,35,35,35,35,35,35,35,35,35,35
_Gen_P_MW.05,444.45,458.33,472.21,486.1,500.0,513.92,527.84,541.77,555.71,569.66,...,451.55,508.81,320.0,320.0,320.0,320.0,320.0,320.0,320.0,320.0
_Gen_Q_mvar.05,-33.69,-26.95,-20.01,-12.85,-5.48,2.11,9.93,17.97,26.24,34.75,...,135.92,208.42,-6.96,-6.02,-3.8,-0.27,4.61,9.72,16.07,23.91
"_Gen_bus_no,_status.06",36,36,36,36,36,36,36,36,36,36,...,36,36,36,36,36,36,36,36,36,36
_Gen_P_MW.06,444.45,458.33,472.21,486.1,500.0,513.92,527.84,541.77,555.71,569.66,...,451.55,508.81,320.0,320.0,320.0,320.0,320.0,320.0,320.0,320.0
_Gen_Q_mvar.06,-26.49,-21.5,-16.36,-11.06,-5.59,0.04,5.84,11.82,17.96,24.29,...,52.42,97.15,-34.41,-33.89,-32.65,-30.68,-27.96,-25.11,-21.57,-17.2
"_Gen_bus_no,_status.07",37,37,37,37,37,37,37,37,37,37,...,37,37,37,37,37,37,37,37,37,37
_Gen_P_MW.07,444.45,458.33,472.21,486.1,500.0,513.92,527.84,541.77,555.71,569.66,...,680.0,680.0,388.09,457.48,527.59,598.45,670.08,680.0,680.0,680.0
_Gen_Q_mvar.07,-45.93,-42.01,-37.95,-33.76,-29.43,-24.96,-20.35,-15.6,-10.7,-5.65,...,12.85,33.11,-76.96,-74.72,-70.13,-63.12,-53.58,-48.68,-43.85,-38.01
"_Gen_bus_no,_status.08",38,38,38,38,38,38,38,38,38,38,...,38,38,38,38,38,38,38,38,38,38
_Gen_P_MW.08,401.77,401.64,401.51,401.39,401.27,401.16,401.05,400.95,400.85,400.76,...,396.03,395.12,403.97,403.84,403.69,403.52,403.34,402.8,402.14,401.43
_Gen_Q_mvar.08,-43.62,-40.66,-37.62,-34.51,-31.32,-28.04,-24.69,-21.25,-17.73,-14.12,...,-10.15,7.14,-66.58,-65.95,-64.55,-62.37,-59.36,-56.34,-52.76,-48.5
"_Gen_bus_no,_status.09",39,39,39,39,39,39,39,39,39,39,...,39,39,39,39,39,39,39,39,39,39
_Gen_P_MW.09,138.89,143.23,147.57,151.91,156.25,160.6,164.95,169.3,173.66,178.02,...,850.0,850.0,121.28,142.96,164.87,187.02,209.4,271.13,339.66,408.93
_Gen_Q_mvar.09,-22.63,-12.46,-2.13,8.37,19.04,29.88,40.9,52.1,63.48,75.06,...,-63.44,-49.38,-141.12,-141.51,-141.08,-139.81,-137.68,-139.72,-140.12,-137.89
_Load_bus_no,3,3,3,3,3,3,3,3,3,3,...,3,3,3,3,3,3,3,3,3,3
_Load_P_MW,196.95,202.44,207.94,213.44,218.93,224.43,229.93,235.42,240.92,246.42,...,122.63,122.63,122.63,122.63,122.63,122.63,122.63,122.63,122.63,122.63
_LOad_Q_mvar,1.47,1.51,1.55,1.59,1.63,1.67,1.71,1.75,1.8,1.84,...,0.91,0.91,0.91,0.91,0.91,0.91,0.91,0.91,0.91,0.91
_Load_bus_no.01,4,4,4,4,4,4,4,4,4,4,...,4,4,4,4,4,4,4,4,4,4
_Load_P_MW.01,305.82,314.36,322.89,331.43,339.96,348.5,357.03,365.57,374.1,382.64,...,190.41,190.41,190.41,190.41,190.41,190.41,190.41,190.41,190.41,190.41
_LOad_Q_mvar.01,112.54,115.68,118.82,121.96,125.11,128.25,131.39,134.53,137.67,140.81,...,70.07,70.07,70.07,70.07,70.07,70.07,70.07,70.07,70.07,70.07
_Load_bus_no.02,7,7,7,7,7,7,7,7,7,7,...,7,7,7,7,7,7,7,7,7,7
_Load_P_MW.02,143.0,146.99,150.98,154.97,158.97,162.96,166.95,170.94,174.93,178.92,...,89.04,89.04,89.04,89.04,89.04,89.04,89.04,89.04,89.04,89.04
_LOad_Q_mvar.02,51.38,52.81,54.25,55.68,57.11,58.55,59.98,61.42,62.85,64.28,...,31.99,31.99,31.99,31.99,31.99,31.99,31.99,31.99,31.99,31.99
_Load_bus_no.03,8,8,8,8,8,8,8,8,8,8,...,8,8,8,8,8,8,8,8,8,8
_Load_P_MW.03,319.28,328.19,337.1,346.01,354.92,363.83,372.74,381.65,390.56,399.47,...,198.79,198.79,198.79,198.79,198.79,198.79,198.79,198.79,198.79,198.79
_LOad_Q_mvar.03,107.65,110.65,113.66,116.66,119.67,122.67,125.67,128.68,131.68,134.69,...,67.03,67.03,67.03,67.03,67.03,67.03,67.03,67.03,67.03,67.03
_Load_bus_no.04,12,12,12,12,12,12,12,12,12,12,...,12,12,12,12,12,12,12,12,12,12
_Load_P_MW.04,5.2,5.34,5.49,5.63,5.78,5.92,6.07,6.21,6.36,6.5,...,3.24,3.24,3.24,3.24,3.24,3.24,3.24,3.24,3.24,3.24
_LOad_Q_mvar.04,53.82,55.33,56.83,58.33,59.83,61.34,62.84,64.34,65.84,67.34,...,33.51,33.51,33.51,33.51,33.51,33.51,33.51,33.51,33.51,33.51
_Load_bus_no.05,15,15,15,15,15,15,15,15,15,15,...,15,15,15,15,15,15,15,15,15,15
_Load_P_MW.05,195.72,201.19,206.65,212.11,217.57,223.04,228.5,233.96,239.42,244.89,...,121.86,121.86,121.86,121.86,121.86,121.86,121.86,121.86,121.86,121.86
_LOad_Q_mvar.05,93.58,96.19,98.8,101.42,104.03,106.64,109.25,111.86,114.47,117.09,...,58.27,58.27,58.27,58.27,58.27,58.27,58.27,58.27,58.27,58.27
_Load_bus_no.06,16,16,16,16,16,16,16,16,16,16,...,16,16,16,16,16,16,16,16,16,16
_Load_P_MW.06,201.47,207.1,212.72,218.34,223.97,229.59,235.21,240.83,246.46,252.08,...,125.44,125.44,125.44,125.44,125.44,125.44,125.44,125.44,125.44,125.44
_LOad_Q_mvar.06,19.76,20.31,20.86,21.41,21.96,22.51,23.06,23.62,24.17,24.72,...,12.3,12.3,12.3,12.3,12.3,12.3,12.3,12.3,12.3,12.3
_Load_bus_no.07,18,18,18,18,18,18,18,18,18,18,...,18,18,18,18,18,18,18,18,18,18
_Load_P_MW.07,96.64,99.34,102.03,104.73,107.43,110.12,112.82,115.52,118.22,120.91,...,60.17,60.17,60.17,60.17,60.17,60.17,60.17,60.17,60.17,60.17
_LOad_Q_mvar.07,18.35,18.86,19.37,19.89,20.4,20.91,21.42,21.93,22.45,22.96,...,11.42,11.42,11.42,11.42,11.42,11.42,11.42,11.42,11.42,11.42
_Load_bus_no.08,20,20,20,20,20,20,20,20,20,20,...,20,20,20,20,20,20,20,20,20,20

In [ ]:
for col in lf.columns:
    if col.startswith("_line_bus_no_To") and len(unique := lf[col].unique()) > 1:
        print(lf[col].unique())

In [ ]:
joblib.load("../data/interscada/interim/pl/topology_cols.joblib.z")

{'_gen_status',
 '_gen_status.01',
 '_gen_status.02',
 '_gen_status.03',
 '_gen_status.04',
 '_gen_status.05',
 '_gen_status.06',
 '_gen_status.07',
 '_gen_status.08',
 '_gen_status.09',
 'line_status_01_02',
 'line_status_01_40_p1',
 'line_status_01_40_p2',
 'line_status_02_03',
 'line_status_02_25',
 'line_status_03_04',
 'line_status_03_18',
 'line_status_04_05',
 'line_status_04_14',
 'line_status_05_06',
 'line_status_05_08',
 'line_status_06_07',
 'line_status_06_11',
 'line_status_07_08',
 'line_status_08_09',
 'line_status_09_40',
 'line_status_10_11',
 'line_status_10_13',
 'line_status_13_14',
 'line_status_14_15',
 'line_status_15_16',
 'line_status_16_17',
 'line_status_16_19',
 'line_status_16_21',
 'line_status_16_24',
 'line_status_17_18',
 'line_status_17_27',
 'line_status_21_22',
 'line_status_21_42',
 'line_status_22_23',
 'line_status_23_24',
 'line_status_25_26',
 'line_status_26_27',
 'line_status_28_29',
 'line_status_41_26',
 'line_status_41_28',
 'line_status_41_29'}

In [ ]:
tsa = pd.read_pickle("../data/interscada/interim/pl/tsa.pkl")
with pd.option_context("display.max_rows", None):
    display(tsa.head(20))

,state,experiment,Location,CCT,critical_generator,Crit_gen,voltage_level_kV
0,SET_0001__Point_no.___10,1,BUS1,0.500,NaN,<NA>,<NA>
1,SET_0001__Point_no.___11,1,BUS1,0.500,NaN,<NA>,<NA>
2,SET_0001__Point_no.___12,1,BUS1,0.500,NaN,<NA>,<NA>
3,SET_0001__Point_no.___13,1,BUS1,0.474,37 [BUS37 13.8],37,13.8
4,SET_0001__Point_no.___14,1,BUS1,0.446,37 [BUS37 13.8],37,13.8
5,SET_0001__Point_no.___15,1,BUS1,0.397,34 [BUS34 13.8],34,13.8
6,SET_0001__Point_no.___16,1,BUS1,0.367,34 [BUS34 13.8],34,13.8
7,SET_0001__Point_no.___17,1,BUS1,0.337,34 [BUS34 13.8],34,13.8
8,SET_0001__Point_no.___18,1,BUS1,0.310,34 [BUS34 13.8],34,13.8
9,SET_0001__Point_no.___19,1,BUS1,0.282,34 [BUS34 13.8],34,13.8
10,SET_0001__Point_no.___20,1,BUS1,0.249,34 [BUS34 13.8],34,13.8
11,SET_0001__Point_no.____2,1,BUS1,0.500,NaN,<NA>,<NA>
12,SET_0001__Point_no.____3,1,BUS1,0.500,NaN,<NA>,<NA>
13,SET_0001__Point_no.____4,1,BUS1,0.500,NaN,<NA>,<NA>
14,SET_0001__Point_no.____5,1,BUS1,0.500,NaN,<NA>,<NA>
15,SET_0001__Point_no.____6,1,BUS1,0.500,NaN,<NA>,<NA>
16,SET_0001__Point_no.____7,1,BUS1,0.500,NaN,<NA>,<NA>
17,SET_0001__Point_no.____8,1,BUS1,0.500,NaN,<NA>,<NA>
18,SET_0001__Point_no.____9,1,BUS1,0.500,NaN,<NA>,<NA>
19,SET_0002__Point_no.___10,1,BUS1,0.500,NaN,<NA>,<NA>

In [ ]:
set(tsa["critical_generator"].unique())

{'30 [BUS30       13.8]',
 '31 [BUS31       13.8]',
 '32 [BUS32       13.8]',
 '33 [BUS33       13.8]',
 '34 [BUS34       13.8]',
 '35 [BUS35       13.8]',
 '36 [BUS36       13.8]',
 '37 [BUS37       13.8]',
 '38 [BUS38       13.8]',
 '39 [BUS39       13.8]',
 nan}

## French dataset

In [ ]:
lf = pd.read_pickle("../data/interscada/interim/fr/lf.pkl")

with pd.option_context("display.max_rows", None):
    display(lf.head().T)

scenario             scenario1     scenario2     scenario3     scenario4  \
n_buses           3.150000e+02  3.030000e+02  2.980000e+02  3.030000e+02
V_1ARGIP7_0       4.071214e+02  4.180513e+02  4.111542e+02  4.121699e+02
angle_1ARGIP7_0   1.440370e+01 -1.081674e+00  1.982737e+00 -3.215975e+01
Pgen_1ARGIP7_0    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
Qgen_1ARGIP7_0    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
Pload_1ARGIP7_0   1.718931e+02  8.436507e+01  1.643812e+02  1.156505e+02
Qload_1ARGIP7_0  -1.242287e+01 -2.074287e+00 -5.432106e+00  1.008517e+01
V_1AYREP7_0       4.099098e+02  4.087543e+02  4.072485e+02  4.057500e+02
angle_1AYREP7_0   6.946738e+00  1.227885e-01  2.573437e-02 -1.927745e+01
Pgen_1AYREP7_0    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
Qgen_1AYREP7_0    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
Pload_1AYREP7_0   5.066468e+01 -3.214697e+01 -7.029306e+00 -2.052897e+01
Qload_1AYREP7_0  -1.764124e+01 -2.717906e+01 -2.915434e+01 -1.229397e+01
V_1B.CAP7_0       4.081915e+02  4.109556e+02  4.079680e+02  4.052872e+02
angle_1B.CAP7_0  -5.319167e+00 -4.140543e+00 -6.130345e+00 -2.086413e+01
Pgen_1B.CAP7_0    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
Qgen_1B.CAP7_0    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
Pload_1B.CAP7_0   1.612011e+02  9.759078e+01  1.331687e+02  1.670336e+02
Qload_1B.CAP7_0  -1.550102e+00 -2.090650e+01 -2.260706e+01 -1.022749e+01
V_1BEZAP7_0       4.076283e+02  4.117873e+02  4.112252e+02  4.058847e+02
angle_1BEZAP7_0  -1.654656e+01 -1.137791e+01 -1.130664e+01  1.136451e+01
Pgen_1BEZAP7_0    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
Qgen_1BEZAP7_0    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
Pload_1BEZAP7_0   7.326461e+01  8.770273e+01  8.505603e+01  1.969122e+02
Qload_1BEZAP7_0   1.236832e+00 -1.107597e+00  8.089531e+00 -1.180020e+01
V_1BIANP7_0       4.098539e+02  4.119251e+02  4.084725e+02  4.055268e+02
angle_1BIANP7_0  -5.840191e+00 -4.659277e+00 -6.631623e+00 -2.148090e+01
Pgen_1BIANP7_0    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
Qgen_1BIANP7_0    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
Pload_1BIANP7_0   2.236734e+02  1.677822e+02  2.137725e+02  2.660626e+02
Qload_1BIANP7_0  -2.319560e+01 -4.169859e+01 -3.854956e+01 -1.913940e+01
V_1CAZAP7_0       3.969891e+02  4.026295e+02           NaN           NaN
angle_1CAZAP7_0   1.310171e+01  2.933676e+00           NaN           NaN
Pgen_1CAZAP7_0    0.000000e+00  0.000000e+00           NaN           NaN
Qgen_1CAZAP7_0    0.000000e+00  0.000000e+00           NaN           NaN
Pload_1CAZAP7_0  -4.914698e+01 -1.257293e+01           NaN           NaN
Qload_1CAZAP7_0   5.301441e+01  3.236684e+01           NaN           NaN
V_1CERGP7_0       4.145408e+02  4.122710e+02  4.116531e+02  4.096802e+02
angle_1CERGP7_0  -1.570133e+01 -6.313634e+00 -1.597415e+01 -1.311862e+01
Pgen_1CERGP7_0    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
Qgen_1CERGP7_0    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
Pload_1CERGP7_0   1.005705e+02  7.522096e+01  9.581760e+01  1.136301e+02
Qload_1CERGP7_0  -2.969077e+01 -1.375108e+01 -1.950723e+01 -3.269383e+01
V_1CHARP7_0       4.131863e+02  4.162510e+02  4.107018e+02  4.085182e+02
angle_1CHARP7_0  -3.240670e+00 -2.283668e+00 -3.345052e+00 -4.962277e+00
Pgen_1CHARP7_0    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
Qgen_1CHARP7_0    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
Pload_1CHARP7_0   1.618862e+02  1.536507e+02  1.450713e+02  1.458849e+02
Qload_1CHARP7_0  -4.187637e+01 -4.906064e+01 -2.607736e+01 -2.340068e+01
V_1CIROP7_0       4.086821e+02  4.112355e+02  4.090374e+02  4.031771e+02
angle_1CIROP7_0  -1.017128e+01 -2.661696e+00 -1.085118e+01 -1.174307e+01
Pgen_1CIROP7_0    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
Qgen_1CIROP7_0    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
Pload_1CIROP7_0   1.886841e+02  1.574668e+02  1.385635e+02  9.613325e+01
Qload_1CIROP7_0  -1.994475e+01 -1.167188e+01 -7.147003e+00  6.207291e+00
V_1CORNP7_0       4.086220e+02  4.109417e+02  4.097275e+02  4.048180e+02
angle_1CORNP7_0  -1.318273e+01 -9.828597e+00 -1.141139e+01  1.396683e+00
Pgen_1CORNP7_0    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
Qgen_1CORNP7_0    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
Pload_1CORNP7_0   2.107433e+02  1.647915e+02  2.410614e+02 -2.639899e+01
Qload_1CORNP7_0  -1.601768e+01 -2.035919e+00  6.950150e-01  3.630564e+01
V_1DAMBP7_0       4.094704e+02  4.134566e+02  4.108602e+02  4.099715e+02
angle_1DAMBP7_0  -4.272614e+00 -3.134979e-01 -9.769831e+00 -1.488975e+01
Pgen_1DAMBP7_0    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
Qgen_1DAMBP7_0    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
Pload_1DAMBP7_0   9.864854e+01  1.929223e+02  2.495847e+02  3.127944e+02
Qload_1DAMBP7_0  -3.399158e+01 -4.575667e+01 -3.856315e+01 -6.290431e+01
V_1FRAS77_0       4.216586e+02  4.230752e+02  4.228626e+02  4.100673e+02
angle_1FRAS77_0  -1.940623e+01 -1.430299e+01 -1.122325e+01  1.010469e+01
Pgen_1FRAS77_0    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
Qgen_1FRAS77_0    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
Pload_1FRAS77_0   1.118495e+02  1.019546e+02  7.654191e+01 -1.252658e+00
Qload_1FRAS77_0  -4.272295e+01 -2.901077e+01 -2.193710e+01 -9.558388e+00
V_1GAUDP7_0       4.093774e+02  4.083837e+02  4.070502e+02  4.054646e+02
angle_1GAUDP7_0   7.045510e+00  3.723339e-01  2.812724e+00 -1.950627e+01
Pgen_1GAUDP7_0    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
Qgen_1GAUDP7_0    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
Pload_1GAUDP7_0   1.636562e+02  1.003766e+02  1.407172e+02  9.008767e+01
Qload_1GAUDP7_0  -4.768970e+01 -5.052828e+01 -5.008234e+01 -3.642950e+01
V_1GEN.P7_0       4.072346e+02  4.126952e+02  4.130542e+02  4.090803e+02
angle_1GEN.P7_0  -1.190873e+01 -9.370504e+00 -1.366258e+01 -5.199491e+00
Pgen_1GEN.P7_0    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
Qgen_1GEN.P7_0    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
Pload_1GEN.P7_0   2.104736e+02  2.132254e+02  4.539066e+02  3.754409e+02
Qload_1GEN.P7_0   6.917217e+00 -5.845253e+00 -3.409995e+01 -9.850243e+00
V_1GROSP7_0       4.105057e+02  4.137632e+02  4.115457e+02  4.063104e+02
angle_1GROSP7_0  -8.326158e+00 -8.348066e+00 -1.049737e+01 -8.641042e+00
Pgen_1GROSP7_0    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
Qgen_1GROSP7_0    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
Pload_1GROSP7_0   1.192390e+02  2.921597e+02  3.306538e+02  4.431419e+02
Qload_1GROSP7_0  -1.110165e+01 -1.439387e+01 -1.127521e+01 -7.938568e+00
V_1LESQP7_0       4.051868e+02  4.067198e+02  4.042077e+02  4.039238e+02
angle_1LESQP7_0   8.054284e+00  1.432575e+00  6.482497e-01 -2.316613e+01
Pgen_1LESQP7_0    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
Qgen_1LESQP7_0    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
Pload_1LESQP7_0   2.461492e+02  1.698030e+02  2.139755e+02  2.489683e+02
Qload_1LESQP7_0  -2.639606e+01 -4.977998e+01 -4.556342e+01 -3.041770e+01
V_1LIMEP7_0       4.063319e+02  4.065872e+02  4.058870e+02  4.035001e+02
angle_1LIMEP7_0  -1.389567e+01 -4.588905e+00 -1.355665e+01 -3.856758e+00
Pgen_1LIMEP7_0    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
Qgen_1LIMEP7_0    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
Pload_1LIMEP7_0   1.912638e+02  1.847673e+02  2.037861e+02  1.012612e+02
Qload_1LIMEP7_0  -2.193386e+01 -2.767624e+01 -2.557375e+01 -8.813431e+00
V_1MARMP7_0       4.040648e+02           NaN           NaN           NaN
angle_1MARMP7_0  -3.184589e+00           NaN           NaN           NaN
Pgen_1MARMP7_0    0.000000e+00           NaN           NaN           NaN
Qgen_1MARMP7_0    0.000000e+00           NaN           NaN           NaN
Pload_1MARMP7_0   1.694817e+02           NaN           NaN           NaN
Qload_1MARMP7_0   4.317356e+01           NaN           NaN           NaN
V_1MAZUP7_0       4.053622e+02  4.079208e+02  4.071607e+02  4.008675e+02
angle_1MAZUP7_0  -1.691647e+01 -1.178832e+01 -1.376974e+01  1.188978e+01
Pgen_1MAZUP7_0    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
Qgen_1MAZUP7_0    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
Pload_1MAZUP7_0   6.999131e+01  8.238388e+01  4.976879e+01 -2.930831e+01
Qload_1MAZUP7_0   6.497296e+00  5.867285e+00  7.709509e+00  8.249528e+00
V_1MEZEP7_0       4.120787e+02  4.124808e+02  4.104818e+02  4.059595e+02
angle_1MEZEP7_0  -1.620048e+01 -6.829251e+00 -1.620539e+01 -1.674295e+01
Pgen_1MEZEP7_0    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
Qgen_1MEZEP7_0    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
Pload_1MEZEP7_0   1.826089e+02  1.410591e+02  1.539488e+02  2.609779e+02
Qload_1MEZEP7_0  -2.678213e+01 -1.875086e+01 -1.700057e+01 -2.692451e+01
V_1MQISP7_0       4.109573e+02  4.151357e+02  4.115888e+02  4.095615e+02
angle_1MQISP7_0   3.517512e+00  4.298107e-01 -2.904934e+00 -2.555548e+01
Pgen_1MQISP7_0    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
Qgen_1MQISP7_0    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
Pload_1MQISP7_0   1.439408e+02  1.315838e+02  1.373493e+02  1.747499e+02
Qload_1MQISP7_0  -4.863583e+01 -6.108889e+01 -5.060088e+01 -4.462932e+01
V_1NEOUP7_0       4.066267e+02  4.049959e+02  4.032608e+02  4.030690e+02
angle_1NEOUP7_0  -1.962661e+00 -1.494223e+00 -2.365336e+00 -1.593794e+01
Pgen_1NEOUP7_0    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
Qgen_1NEOUP7_0    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
Pload_1NEOUP7_0   6.934739e+01  4.767745e+01  4.724755e+01  4.577627e+01
Qload_1NEOUP7_0   1.560204e+00  1.494461e+01  9.707844e+00  6.114098e+00
V_1REALP7_0       4.071155e+02  4.074082e+02  4.056341e+02  4.038044e+02
angle_1REALP7_0  -2.540947e+00 -1.729551e+00 -2.389077e+00 -1.591620e+01
Pgen_1REALP7_0    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
Qgen_1REALP7_0    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
Pload_1REALP7_0   2.415055e+02  1.855167e+02  1.935886e+02  2.186019e+02
Qload_1REALP7_0  -2.758369e+01 -2.191274e+01 -2.252548e+01 -2.063988e+01
V_1RUEYP7_0       4.011982e+02  4.046864e+02  4.046213e+02  4.007211e+02
angle_1RUEYP7_0   6.489870e+00 -1.600857e-01 -3.073029e+00 -1.716126e+01
Pgen_1RUEYP7_0    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
Qgen_1RUEYP7_0    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
Pload_1RUEYP7_0   2.504552e+01 -1.290304e+02 -9.931978e+01 -1.696548e+02
Qload_1RUEYP7_0   3.170053e+01 -2.264672e+01 -1.895786e+01  1.861206e+00
V_1RULHP7_0       4.059613e+02  4.045987e+02  4.037845e+02  3.995317e+02
angle_1RULHP7_0  -1.382020e+00  4.727585e-01 -4.620432e+00 -1.005621e+01
Pgen_1RULHP7_0    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
Qgen_1RULHP7_0    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
Pload_1RULHP7_0   5.474929e+01  7.247270e+01  5.857741e+01  1.024830e+02
Qload_1RULHP7_0   2.070538e+01  3.055093e+01  3.354013e+01  2.933470e+01
V_1SEREP7_0       4.092227e+02           NaN           NaN           NaN
angle_1SEREP7_0  -9.002790e+00           NaN           NaN           NaN
Pgen_1SEREP7_0    0.000000e+00           NaN           NaN           NaN
Qgen_1SEREP7_0    0.000000e+00           NaN           NaN           NaN
Pload_1SEREP7_0   4.058452e+01           NaN           NaN           NaN
Qload_1SEREP7_0   2.161786e+01           NaN           NaN           NaN
V_1TAMAP7_0       4.099479e+02  4.106136e+02  4.094915e+02  4.050207e+02
angle_1TAMAP7_0   4.463359e+00  1.297136e+00  2.320358e+00 -1.573953e+01
Pgen_1TAMAP7_0    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
Qgen_1TAMAP7_0    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
Pload_1TAMAP7_0   1.655112e+02  1.164659e+02  1.390188e+02  1.593650e+02
Qload_1TAMAP7_0  -3.395904e+01 -3.904340e+01 -3.749802e+01 -3.000620e+01
V_1VALDP7_0       4.085319e+02  4.097365e+02  4.095483e+02  4.067221e+02
angle_1VALDP7_0  -4.807031e-01  2.866676e+00 -3.263075e+00 -1.681067e+01
Pgen_1VALDP7_0    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
Qgen_1VALDP7_0    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
Pload_1VALDP7_0   1.973983e+02  1.431130e+02  1.536537e+02  1.446404e+02
Qload_1VALDP7_0  -1.393981e+01 -3.043562e+01 -1.487138e+01 -1.106685e+01
V_1VERFP7_0       4.057206e+02  4.057438e+02  4.032571e+02  4.027539e+02
angle_1VERFP7_0   8.058844e+00  1.091231e+00  1.312400e+00 -2.210926e+01
Pgen_1VERFP7_0    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
Qgen_1VERFP7_0    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
Pload_1VERFP7_0   2.104444e+02  1.445135e+02  1.819295e+02  1.962980e+02
Qload_1VERFP7_0  -8.674789e+00 -2.115029e+01 -2.334315e+01 -8.812248e+00
V_1VIELP7_0       4.105680e+02           NaN           NaN           NaN
angle_1VIELP7_0  -1.025910e+01           NaN           NaN           NaN
Pgen_1VIELP7_0    0.000000e+00           NaN           NaN           NaN
Qgen_1VIELP7_0    0.000000e+00           NaN           NaN           NaN
Pload_1VIELP7_0   8.204109e+01           NaN           NaN           NaN
Qload_1VIELP7_0   1.372601e+01           NaN           NaN           NaN
V_1YVE.P7_0       4.134120e+02  4.141580e+02  4.121456e+02  4.078055e+02
angle_1YVE.P7_0  -1.485774e+01 -6.494902e+00 -1.521885e+01 -1.596556e+01
Pgen_1YVE.P7_0    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
Qgen_1YVE.P7_0    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
Pload_1YVE.P7_0   1.157648e+02  1.283868e+02  1.059974e+02  2.304879e+02
Qload_1YVE.P7_0  -3.464127e+01 -3.212426e+01 -2.830221e+01 -3.979517e+01
V_2ALBEP7_0       4.056498e+02  4.063376e+02  4.097671e+02  4.042004e+02
angle_2ALBEP7_0  -1.047020e+01 -8.402549e+00 -7.291401e+00  1.521583e+00
Pgen_2ALBEP7_0    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
Qgen_2ALBEP7_0    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
Pload_2ALBEP7_0   1.517822e+02  1.404941e+02  1.919913e+02  1.268615e+01
Qload_2ALBEP7_0  -2.987200e+01 -1.381116e+01 -1.997419e+01  1.896231e+01
V_2ARGIP7_0       4.070912e+02  4.181066e+02  4.111677e+02  4.122844e+02
angle_2ARGIP7_0   1.454026e+01 -1.019045e+00  2.110881e+00 -3.207014e+01
Pgen_2ARGIP7_0    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
Qgen_2ARGIP7_0    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
Pload_2ARGIP7_0   1.609825e+02  7.907292e+01  1.539290e+02  1.082808e+02
Qload_2ARGIP7_0  -1.130194e+01 -2.350807e+00 -4.853035e+00  9.270180e+00
V_2AYREP7_0       4.077121e+02  4.066739e+02  4.051220e+02  4.037221e+02
angle_2AYREP7_0   6.945800e+00  7.355194e-02 -1.013854e-02 -1.931666e+01
Pgen_2AYREP7_0    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
Qgen_2AYREP7_0    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
Pload_2AYREP7_0   5.385309e+01 -2.995058e+01 -4.369030e+00 -1.869561e+01
Qload_2AYREP7_0   3.159511e+00 -9.586922e+00 -1.085425e+01  5.661719e+00
V_2BREUP71_0      4.034175e+02  4.079520e+02  4.080904e+02  4.039724e+02
angle_2BREUP71_0  3.825817e+00  8.794761e-01 -4.096873e+00 -1.715086e+01
Pgen_2BREUP71_0   0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
Qgen_2BREUP71_0   0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
Pload_2BREUP71_0 -4.403831e+01  2.411901e+01  5.640862e+00  9.068316e+01
Qload_2BREUP71_0  3.532104e+01  2.870328e+01  3.044602e+01  1.306583e+01
V_2BREUP7_0       4.051708e+02  4.097549e+02  4.098885e+02  4.058732e+02
angle_2BREUP7_0   3.911495e+00  8.612772e-01 -4.087337e+00 -1.727249e+01
Pgen_2BREUP7_0    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
Qgen_2BREUP7_0    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
Pload_2BREUP7_0  -7.258080e+01  3.761385e+01  7.735265e+00  1.453653e+02
Qload_2BREUP7_0   3.762987e+01  2.743650e+01  3.002868e+01  3.058914e+00
V_2CAZAP7_0       3.954454e+02  4.012193e+02           NaN           NaN
angle_2CAZAP7_0   1.361316e+01  3.157419e+00           NaN           NaN
Pgen_2CAZAP7_0    0.000000e+00  0.000000e+00           NaN           NaN
Qgen_2CAZAP7_0    0.000000e+00  0.000000e+00           NaN           NaN
Pload_2CAZAP7_0  -7.031195e+01 -2.186820e+01           NaN           NaN
Qload_2CAZAP7_0   6.215115e+01  4.096087e+01           NaN           NaN
V_2CHARP7_0       4.101375e+02  4.130241e+02  4.093959e+02  4.072763e+02
angle_2CHARP7_0  -2.742241e+00 -1.817989e+00 -2.870499e+00 -4.480309e+00
Pgen_2CHARP7_0    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
Qgen_2CHARP7_0    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
Pload_2CHARP7_0   1.417977e+02  1.346666e+02  1.265812e+02  1.272830e+02
Qload_2CHARP7_0  -2.310180e+01 -2.933679e+01 -1.699128e+01 -1.467640e+01
V_2GAUDP7_0       4.096401e+02  4.086302e+02  4.073173e+02  4.056257e+02
angle_2GAUDP7_0   6.919683e+00  2.980599e-01  2.704549e+00 -1.957417e+01
Pgen_2GAUDP7_0    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
Qgen_2GAUDP7_0    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
Pload_2GAUDP7_0   1.730711e+02  1.059334e+02  1.487296e+02  9.508563e+01
Qload_2GAUDP7_0  -5.075377e+01 -5.323940e+01 -5.310184e+01 -3.821043e+01
V_2H.PAP7_0       4.102722e+02           NaN           NaN           NaN
angle_2H.PAP7_0  -8.797090e+00           NaN           NaN           NaN
Pgen_2H.PAP7_0    0.000000e+00           NaN           NaN           NaN
Qgen_2H.PAP7_0    0.000000e+00           NaN           NaN           NaN
Pload_2H.PAP7_0   1.495675e+02           NaN           NaN           NaN
Qload_2H.PAP7_0   2.843330e+00           NaN           NaN           NaN
V_2LATEP7_0       4.129634e+02  4.146109e+02  4.128656e+02  4.070256e+02
angle_2LATEP7_0  -1.712456e+01 -8.386544e+00 -1.631706e+01 -3.948587e+00
Pgen_2LATEP7_0    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
Qgen_2LATEP7_0    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
Pload_2LATEP7_0   1.277359e+02  1.020882e+02  1.110277e+02  5.553753e+01
Qload_2LATEP7_0  -2.707513e+01 -3.115090e+01 -3.130573e+01 -1.479823e+01
V_2MARTP7_0       4.063778e+02           NaN           NaN  4.110244e+02
angle_2MARTP7_0  -3.377290e+01           NaN           NaN -3.994250e+01
Pgen_2MARTP7_0    0.000000e+00           NaN           NaN  0.000000e+00
Qgen_2MARTP7_0    0.000000e+00           NaN           NaN  0.000000e+00
Pload_2MARTP7_0   3.734831e+02           NaN           NaN  2.943737e+02
Qload_2MARTP7_0  -1.314825e+01           NaN           NaN -1.189211e+01
V_2MAZUP7_0       4.075040e+02  4.100841e+02  4.092996e+02  4.029805e+02
angle_2MAZUP7_0  -1.704261e+01 -1.193780e+01 -1.385344e+01  1.196885e+01
Pgen_2MAZUP7_0    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
Qgen_2MAZUP7_0    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
Pload_2MAZUP7_0   7.645179e+01  9.010639e+01  5.414750e+01 -3.304372e+01
Qload_2MAZUP7_0  -5.356857e+00 -6.327469e+00 -3.945503e+00 -2.584496e+00
V_2MEZEP7_0       4.118072e+02  4.122982e+02  4.103332e+02  4.057411e+02
angle_2MEZEP7_0  -1.582439e+01 -6.539529e+00 -1.588644e+01 -1.619020e+01
Pgen_2MEZEP7_0    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
Qgen_2MEZEP7_0    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
Pload_2MEZEP7_0   1.163847e+02  8.990466e+01  9.813721e+01  1.664062e+02
Qload_2MEZEP7_0  -1.708748e+01 -1.210280e+01 -1.095145e+01 -1.667490e+01
V_2MIONP7_0       4.079199e+02  4.107377e+02  4.090738e+02  4.086516e+02
angle_2MIONP7_0  -1.966283e+00 -1.812124e+00 -2.738518e+00 -5.468428e+00
Pgen_2MIONP7_0    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
Qgen_2MIONP7_0    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
Pload_2MIONP7_0   1.057217e+02  9.925311e+01  1.511554e+02  3.070192e+02
Qload_2MIONP7_0  -3.352246e+01 -4.611986e+01 -3.862995e+01 -5.043987e+01
V_2MORBP7_0       4.136442e+02  4.191865e+02  4.157831e+02  4.118678e+02

In [ ]:
tsa = pd.read_pickle("../data/interscada/interim/fr/tsa.pkl")
with pd.option_context("display.max_rows", None):
    display(tsa.head(20))

         state       CCT       Crit_gen       Location
0    scenario1  0.800000  PENLY7PENLYT1  ARGOEL71PENL5
1    scenario2  0.688672  PENLY7PENLYT1  ARGOEL71PENL5
2    scenario3  0.735547  PENLY7PENLYT1  ARGOEL71PENL5
3    scenario4  0.800000            NaN  ARGOEL71PENL5
4    scenario5  0.764844  PENLY7PENLYT1  ARGOEL71PENL5
5    scenario6  0.800000            NaN  ARGOEL71PENL5
6    scenario7  0.729688  PENLY7PENLYT1  ARGOEL71PENL5
7    scenario8  0.800000            NaN  ARGOEL71PENL5
8    scenario9  0.800000            NaN  ARGOEL71PENL5
9   scenario10  0.800000            NaN  ARGOEL71PENL5
10  scenario11  0.800000            NaN  ARGOEL71PENL5
11  scenario12  0.612500  PENLY7PENLYT1  ARGOEL71PENL5
12  scenario13  0.800000            NaN  ARGOEL71PENL5
13  scenario14  0.800000            NaN  ARGOEL71PENL5
14  scenario15  0.800000            NaN  ARGOEL71PENL5
15  scenario16  0.800000            NaN  ARGOEL71PENL5
16  scenario17  0.800000            NaN  ARGOEL71PENL5
17  scenario18  0.530469  PENLY7PENLYT1  ARGOEL71PENL5
18  scenario19  0.800000            NaN  ARGOEL71PENL5
19  scenario20  0.307813  PENLY7PENLYT1  ARGOEL71PENL5